name: Twitch Clip Processor Daily

on:
  schedule:
    - cron: '0 9 * * *'  # dagelijks om 09:00 UTC
  workflow_dispatch:

jobs:
  process-clips:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        sudo apt update && sudo apt install ffmpeg -y
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Twitch auto script
      run: python twitch_auto.py
        
    - name: Commit and Push video's
      run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Voeg de output map toe (zorg dat er een .gitkeep in zit als de map leeg begint)
          git add output/
          
          # Alleen committen als er daadwerkelijk nieuwe bestanden zijn
          if git diff --staged --quiet; then
            echo "Geen nieuwe video's om te uploaden."
          else
            git commit -m "Nieuwe Twitch clips toegevoegd: $(date +'%Y-%m-%d %H:%M')"
            git push
          fi
    - name: Upload processed clips
      uses: actions/upload-artifact@v4
      with:
        name: twitch-clips
        path: output/*.mp4


              
